services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile  # 開発環境用
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ENV=development
      - DEBUG=1
      - DATABASE_URL=postgresql://djangosample:password@db:5432/djangosample_db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=djangosample_db
      - POSTGRES_USER=djangosample
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: